[package]
name = "bgrt_app"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.33.0", features = ["alloc", "global_allocator", "panic_handler"] }
acpi_sdt = { path = "../acpi_sdt" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
